role_londrinense/urls.py
from calendario import views
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('cadastro/', views.signup, name='signup'),
    path('entrar/', views.signin, name='signin'),
    path('sair/', views.signout, name='signout'),
    path('criar-evento/', views.criar_evento, name='criar_evento'),
    path('all_events/', views.get_eventos, name='get_eventos'),
    path('evento/<int:id_evento>/', views.abrir_evento, name='abrir_evento'),
    path('editar-evento/<int:id_evento>/', views.editar_evento, name='editar_evento'),
    path('deletar-evento/<int:id_evento>/', views.deletar_evento, name='deletar_evento'),
    path('meus-eventos/', views.lista_evento, name='lista_evento'),
    path('favorito/<int:id_evento>/', views.favoritar, name='favoritar'),
    path('favoritos/', views.acessar_favoritos, name='acessar_favoritos'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

calendario/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Evento(models.Model):
    id_evento = models.AutoField(primary_key=True)
    nome_evento = models.TextField()
    descricao = models.TextField()
    data_inicio = models.DateTimeField()
    data_final = models.DateTimeField()
    local_online = models.CharField(choices=[("Local", "Local"),("Online", "Online")], max_length=6)
    faixa_etaria = models.IntegerField()
    endereco = models.TextField(blank=True)
    website = models.TextField()
    politica = models.TextField()
    banner = models.ImageField(null=True, blank=True, upload_to="images/")
    id_usuario = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        db_table = "eventos"

class Favoritos(models.Model):
    id_favorito = models.AutoField(primary_key=True)
    id_evento = models.ForeignKey(Evento, on_delete=models.CASCADE)
    id_usuario = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        db_table = "favoritos"

calendario/forms.py
from django import forms
from .models import Evento
from django.forms import Textarea, TextInput, DateTimeInput, Select, NumberInput, FileInput

class EventoForm(forms.ModelForm):
    class Meta:
        model = Evento
        endereco = forms.CharField(max_length=255, required=False)
        fields = ['nome_evento', 'descricao', 'data_inicio', 'data_final', 'local_online', 'faixa_etaria', 'endereco', 'website', 'politica', 'banner']
        labels = {
            'nome_evento': 'Nome do Evento',
            'descricao': 'Descrição',
            'data_inicio': 'Data de Inicio',
            'data_final': 'Data de Final',
            'local_online': 'Local ou Online?',
            'faixa_etaria': 'Idade Mínima',
            'endereco': 'Endereço',
            'website': 'Website',
            'politica': 'Política do evento',
            'banner': 'Banner do Evento',
        }
        widgets = {
            'nome_evento': TextInput(attrs=({"class": "form-control"})),
            'descricao': Textarea(attrs=({"class": "form-control"})),
            'endereco': TextInput(attrs=({"class": "form-control"})),
            'website': TextInput(attrs=({"class": "form-control"})),
            'politica': TextInput(attrs=({"class": "form-control"})),
            'data_inicio': DateTimeInput(attrs=({"class": "form-control","type":"datetime-local"})),
            'data_final': DateTimeInput(attrs=({"class": "form-control","type":"datetime-local"})),
            'local_online': Select(attrs=({"class": "form-control"})),
            'faixa_etaria': NumberInput(attrs=({"class": "form-control"})),
            'banner': FileInput(attrs=({"class": "form-control"})),
        }

    def clean_nome_evento(self):
        nome_evento = self.cleaned_data['nome_evento']
        if len(nome_evento.strip()) == 0 or nome_evento.isdigit() or len(nome_evento) > 100:
            raise forms.ValidationError('O nome do evento deve conter entre 1 e 100 caracteres e não pode ser somente números ou espaços.')
        return nome_evento

    def clean_descricao(self):
        descricao = self.cleaned_data['descricao']
        if len(descricao) < 20:
            raise forms.ValidationError('A descrição deve conter pelo menos 20 caracteres.')
        return descricao

    def clean(self):
        cleaned_data = super().clean()
        data_inicio = cleaned_data.get('data_inicio')
        data_final = cleaned_data.get('data_final')

        if data_inicio and data_final and data_inicio >= data_final:
            raise forms.ValidationError('A data de início deve acontecer antes da data final.')

        local_online = cleaned_data.get('local_online')
        endereco = cleaned_data.get('endereco')

        if not local_online:
            raise forms.ValidationError('O campo "Local ou Online?" é obrigatório.')

        if local_online == 'Local' and not endereco:
            raise forms.ValidationError('O campo "Endereço" é obrigatório quando o evento é local.')

calendario/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from .models import Evento, Favoritos
from django.http import HttpResponse, JsonResponse 
from django.conf import settings
from django.conf.urls.static import static
from .forms import EventoForm
from django.contrib import messages

# Create your views here.

def verificado(user):
    return user.groups.filter(name='Verificado').exists()

def home(request):
    if verificado(request.user):
        ver = True
    else:
        ver = False

    all_eventos = Evento.objects.all()
    response = []
    for evento in all_eventos:
        response.append({
            "id": evento.id_evento,
            "title": evento.nome_evento,
            "start": evento.data_inicio.strftime("%m/%d/%Y, %H:%M:%S"),
            "end": evento.data_final.strftime("%m/%d/%Y, %H:%M:%S"),
        })
    if request.user.is_authenticated:
        return render(request, 'home.html', {"response": response, "verificado": ver})
    else:
        return redirect('signin')

def signin(request):
    if request.method == 'GET':
        return render(request, 'signin.html',{
            'form': AuthenticationForm
        })
    else:
        user = authenticate(
            request,
            username=request.POST['username'],
            password=request.POST['senha']
        )

        if user.is_authenticated:
            login(request, user)
            return redirect('home')
        else:
            return render(request, 'signin.html', {
                'form': AuthenticationForm,
                'error': 'Usuário ou senha incorretos'
            })

def signup(request):
    if request.method == 'GET':
        return render(request, 'signup.html',{
            'form': UserCreationForm
        })
    else:
        if request.POST['confirmarSenha'] == request.POST['senha']:
            try:
                user = User.objects.create_user(username=request.POST['username'],
                                               first_name=request.POST['nome'],
                                               last_name=request.POST['sobrenome'],
                                               email=request.POST['email'],
                                               password=request.POST['senha'])
                user.save()
                login(request, user)
                return redirect('signin')
            except:
                return render(request, 'signup.html', {
                            'form' : UserCreationForm,
                            'error' : 'Usuário Já Existe'
                            })
            
        return render(request, 'signup.html', {
            'form': UserCreationForm,
            'error': 'As senhas são diferentes'
        })

def signout(request):
    logout(request)
    return redirect('signin')

def favoritar(request, id_evento):
    user = request.user
    evento = Evento.objects.get(id_evento=id_evento)
    
    favorito_existe = Favoritos.objects.filter(id_evento=evento, id_usuario=user)

    if favorito_existe:
        favorito_existe.delete()
    else:
        Favoritos.objects.create(id_evento=evento, id_usuario=user)
    
    return redirect('abrir_evento', id_evento=id_evento)
    
def criar_evento(request):
    if request.user.is_authenticated:
        if verificado(request.user):
            if request.method == 'POST':
                form = EventoForm(request.POST, request.FILES)
                if form.is_valid():
                    evento = form.save(commit=False)
                    evento.id_usuario = request.user
                    evento.save()
                    return redirect('home')
            else:
                form = EventoForm()
                return render(request, 'evento/criar-evento.html', {'form': form})
        else:
            return redirect('home')
    else:
        return redirect('signin')


def get_eventos(request):
    get_eventos = Evento.objects.all()
    response = []
    for evento in get_eventos:
        response.append({
            'id': evento.id_evento,
            'title': evento.nome_evento,
            'id': evento.id_evento,
            'start': evento.data_inicio.strftime("%m/%d/%Y, %H:%M:%S"),
            'end': evento.data_final.strftime("%m/%d/%Y, %H:%M:%S"),
        })

    return JsonResponse(response, safe=False) 

def abrir_evento(request,id_evento):
    evento = get_object_or_404(Evento, pk=id_evento)

    if Favoritos.objects.filter(id_evento=evento, id_usuario=request.user):
        favorito_existe = True
    else:
        favorito_existe = False

    return render(request, 'evento/evento.html', {'evento': evento ,'favorito': favorito_existe})

def editar_evento(request,id_evento):
    evento = Evento.objects.get(pk=id_evento)
    
    form = EventoForm(request.POST or None, request.FILES or None, instance=evento)
    if form.is_valid():
        form.save()
        return redirect('lista_evento')

    return render(request, 'evento/editar-evento.html', {'form': form, 'evento': evento})

def deletar_evento(request,id_evento):
    evento = Evento.objects.get(pk=id_evento)
    if not request.user.is_authenticated:
        messages.success(request, ("Você não esta logado!"))
        return redirect('lista_evento')
    elif evento.id_usuario == request.user:
        evento.delete()
        messages.success(request, ("Evento deletado com sucesso!"))
        return redirect('lista_evento')
    else:
        messages.success(request, ("Você não possui permissão para deletar este evento!"))
        return redirect('lista_evento')

def lista_evento(request):
    if request.user.is_authenticated:
        eventos = Evento.objects.filter(id_usuario=request.user)
        return render(request, 'evento/lista-evento.html', {"eventos": eventos})
    else:
        return redirect('home')

def acessar_favoritos(request):
    if request.user.is_authenticated:
        favoritos = Favoritos.objects.filter(id_usuario=request.user).select_related('id_evento')
    
    return render(request, 'evento/favoritos.html', {'favoritos': favoritos})

calendario/templates/evento/criar-evento.html
{% extends 'partials/menu.html' %}

{% block content %}

{% if user.is_authenticated %}
<div class="container">
    <div class="card m-5" style="width: 1000px;">
        <div class="card-body">
            <div class="row">
                <div class="col">
                    <h3 class="mb-3">Cadastrar</h3>
                    <form method="POST" enctype="multipart/form-data" id="formEvento">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Cadastrar</button>
                        <div id="errorEndereco" style="display: none; color: red;">O endereço é obrigatório para eventos locais.</div>
                        <div id="errorData" style="display: none; color: red;">A data final deve ser posterior à data de início.</div>
                    </form>
                </div>
                <div class="col text-center">
                    {% load static %}
                </div>
            </div>
        </div>
    </div>
</div>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
        $(document).ready(function () {
            $("#id_local_online").change(function () {
                if ($(this).val() === "Local") {
                    $("#id_endereco").show();
                    $("#id_endereco").prop("required", true);
                } else {
                    $("#id_endereco").hide();
                    $("#id_endereco").prop("required", false);
                }
            });

            $("#formEvento").submit(function (event) {
                var dataInicio = new Date($("#id_data_inicio").val());
                var dataFinal = new Date($("#id_data_final").val());

                if (dataFinal <= dataInicio) {
                    $("#errorData").show();
                    event.preventDefault();
                } else {
                    $("#errorData").hide();
                }

                if ($("#idlocal_online").val() === "local" && $("#id_endereco").val().trim() === "") {
                    $("#errorEndereco").show();
                    event.preventDefault();
                } else {
                    $("#errorEndereco").hide();
                }
            });
        });
</script>
{% endif %}
{% endblock %}

calendario/templates/evento/deletar-evento.html
{% extends 'partials/menu.html' %}

{% block content %}

{% if user.is_authenticated %}
    {% if user.id == evento.id_usuario.id %}
        <div class="container">
            <div class="card m-5" style="width: 1000px;">
                <div class="card-body">
                    <div class="row">
                        <div class="col">
                            <h3 class="mb-3">Editar Evento</h3>
                            <form method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit" class="btn btn-primary" value="Update">Atualizar</button>
                            </form>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    {% else %}
    <h1 class="m-5">Você não pode Editar este Evento!</h1>
    {% endif %}
{% endif %}
{% endblock %}

calendario/templates/evento/editar-evento.html
{% extends 'partials/menu.html' %}

{% block content %}

{% if user.is_authenticated %}
<div class="container">
    <div class="card m-5" style="width: 1000px;">
        <div class="card-body">
            <div class="row">
                {{ evento }}
                <div class="col">
                    <h3 class="mb-3">Editar Evento</h3>
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary" value="Update">Atualizar</button>
                    </form>
                </div>
                <div class="col text-center">

                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

calendario/templates/evento/evento.html
{% extends 'partials/menu.html' %}

{% block content %}
<div class="container mt-5 text-center">
  {% if evento.banner %}
  <img src="{{ evento.banner.url }}" alt="Banner do Evento" class="img-fluid">
  {% endif %}
  <!-- Nome do evento -->
  <h1 class="mt-4" >{{evento.nome_evento}}</h1>
</div>
<div class="container card mt-5 mb-5 card-evento">
  <div class="row m-5 mb-0">
    {% if evento.local_online == 'Local' %}
    <div class="col-md-4">
        <p><strong>Local:</strong></p>
        <p>{{evento.endereco}}</p>
    </div>
    {% else %}
    <div class="col-md-4">
      <p><strong>Local:</strong></p>
      <p>{{evento.local_online}}</p>
    </div>
    {% endif %}
    <div class="col-md-4">
      <p><strong>Data e Horário:</strong></p>
      <p> {{evento.data_inicio}} até</p>
      <p> {{evento.data_final}}</p>
    </div>
    <div class="col-md-4">
      <p><strong>Faixa Etária:</strong></p>
      <p>{{evento.faixa_etaria}}</p>
    </div>
  </div>
  <hr>
  <!-- Descrição do evento -->
  <div class="row m-5 justify-content-sm-around">
    <div class="col-md-4 ">
      <h3><strong>Descrição:</strong></h3>
      <p>{{evento.descricao}}</p>
    </div>
    <div class="col-md-4">
      <h3><strong>Política do Evento</strong></h3>
      <p>{{evento.politica}}</p>
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col m-5">
      <h3 class="m-4"><strong>Website do Evento</strong></h3>
      <ul class="m-4">
          <li><a href="{{evento.website}}" target="_blank">Site Oficial do Evento</a></li>
      </ul>
    </div>
    <div class="col m-5">
      <h3 class="m-4"><strong>Favorite este evento!</strong></h3>
      {% if user.is_authenticated %}
          <form action="{% url 'favoritar' evento.id_evento %}" method="post">
              {% csrf_token %}
              {% if favorito %}
                  <button type="submit" class="btn btn-danger m-4">Remover dos Favoritos</button>
              {% else %}
                  <button type="submit" class="btn btn-primary m-4">Favoritar</button>
              {% endif %}
          </form>
      {% else %}
          <p>Faça login para favoritar este evento.</p>
      {% endif %}
    </div>
  </div>
</div>


{% endblock %}

calendario/templates/evento/favoritos.html
{% extends 'partials/menu.html' %}

{% block content %}

{% if user.is_authenticated %}
<div class="container m-5">
    
    <h1>Meus Eventos Favoritos</h1>
    {% for evento in favoritos %}
    <div class="card m-5" style="width: 1000px; display: flex; flex-direction: row;">
        {% if evento.id_evento.banner %}
        <img src="{{evento.id_evento.banner.url}}" class="card-img-top" alt="Banner do evento" style="height: 500px; width: 500px; padding: 30px;">
        {% endif %}
        <div class="card-body">
          <h3 class="card-title">{{evento.id_evento.nome_evento}}</h3>
          <p class="card-text">{{evento.id_evento.descricao}}</p>
          <p class="card-text">{{evento.id_evento.data_inicio}} até {{evento.id_evento.data_final}}</p>
          <a href="{% url 'abrir_evento' evento.id_evento.id_evento %}" class="btn btn-primary">Acessar Evento</a>
        </div>
    </div>
    {% endfor %}
</div>
{% else %}
<div class="container">
    <h2 class="m-5">Faça o login para adicionar</h2>
</div>
{% endif %}

{% endblock %}

calendario/templates/evento/lista-evento.html
{% extends 'partials/menu.html' %}

{% block content %}

{% if user.is_authenticated %}
<div class="container m-5">
    <h1>Meus Eventos</h1>
    {% for evento in eventos %}

    <div class="card m-5" style="width: 1000px; display: flex; flex-direction: row;">
        {% if eventos.banner %}
        <img src="{{evento.banner.url}}" class="card-img-top" alt="Banner do evento" style="height: 300px; width: 300px;">
        {% endif %}
        <div class="card-body">
          <h3 class="card-title">{{evento.nome_evento}}</h3>
          <p class="card-text">{{evento.descricao}}</p>
          <p class="card-text">{{evento.data_inicio}} até {{evento.data_final}}</p>
          <a href="{% url 'editar_evento' evento.id_evento %}" class="btn btn-primary">Editar Evento</a>
          <a href="{% url 'deletar_evento' evento.id_evento %}" class="btn btn-danger">Deletar Evento</a>
        </div>
      </div>

    {% endfor %}
</div>
{% endif %}

{% endblock %}